# Generated by Django 3.1.2 on 2020-10-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='text',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
