# Generated by Django 3.1.2 on 2020-10-26 15:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201026_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tguser',
            name='text',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='app.tguser')),
            ],
        ),
    ]
